var courses =
 [
     {name: 'Accounting',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipPBmBce6ZfkOmlwuIJVD1NDjLcTmSSd_sVU4MuU', instructor: 'Instructor: John Doe', duration: 'Duration: 3 Months', students: '1452 Students'},
     {name: 'Marketing',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipNl-R42gEWeIpGG_ea8eGi7CsysegWn80mqmyxv', instructor: 'Instructor: Peter Parker', duration: 'Duration: 2 Months', students: '324 Students'},
     {name: 'Computer Programming',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipMC3G_B48GNV_XM_GpGa5TfliMx6_w98ykJP-WH', instructor: 'Instructor: Johny Depp', duration: 'Duration: 6 Months', students: '765 Students'},
     {name: 'Economics',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipOSMMGdhxOlI1X8iJw1oWG0aa0Ga9DndKZsS9aI', instructor: 'Instructor: Kate Winslet', duration: 'Duration: 4 Months', students: '567 Students'},
     {name: 'Digital Marketing',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipMCyTIQ8ZnZOORb3H2UCFPK7rT1UHX9aEh71u0O', instructor: 'Instructor: Ema Watson', duration: 'Duration: 3 Months', students: '987 Students'},
     {name: 'Web Development',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipP0BHnIP2YVbEcKaJUPSjhk8BoJ9JfDnDeyeX9d', instructor: 'Instructor: James Bond', duration: 'Duration: 2 Months', students: '456 Students'},
     {name: 'Graphic Design',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipPBmBce6ZfkOmlwuIJVD1NDjLcTmSSd_sVU4MuU', instructor: 'Instructor: Pirates of the Carribean', duration: 'Duration: 1 Months', students: '987 Students'},
     {name: 'Mathematics',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipNl-R42gEWeIpGG_ea8eGi7CsysegWn80mqmyxv', instructor: 'Instructor: Titanic', duration: 'Duration: 4 Months', students: '4567 Students'},
     {name: 'Management',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipMC3G_B48GNV_XM_GpGa5TfliMx6_w98ykJP-WH', instructor: 'Instructor: Jack Maa', duration: 'Duration: 6 Months', students: '567 Students'},
     {name: 'Human Resource Management',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipOSMMGdhxOlI1X8iJw1oWG0aa0Ga9DndKZsS9aI', instructor: 'Instructor: Elon Mask', duration: 'Duration: 3 Months', students: '457 Students'},
     {name: 'Hotel Management',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipMCyTIQ8ZnZOORb3H2UCFPK7rT1UHX9aEh71u0O', instructor: 'Instructor: Bill Gates', duration: 'Duration: 2 Months', students: '67 Students'},
     {name: 'Business Startup',price: '$10.99', image: 'https://photos.google.com/album/AF1QipMxPkTTXulSx-KAzYs4GJj8S3Z_HtljIRb1OttP/photo/AF1QipP0BHnIP2YVbEcKaJUPSjhk8BoJ9JfDnDeyeX9d', instructor: 'Instructor: Warren Buffet', duration: '1 Months', students: '3425 Students'}
]

export default courses;
